version: '3'

services:
  xpath:
    restart: always
    image: web-a1-xpath
    build: ./src
    container_name: web-a1-xpath
    ports:
      - 0.0.0.0:1001:80
    networks:
      - custom_network_xpath
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB

networks:
  custom_network_xpath:
    driver: bridge
    driver_opts:
        com.docker.network.enable_ipv6: "false"
        com.docker.network.bridge.name: "web-a1-xpath"
